import requests

# Replace 'https://abcdef123.loca.lt' with the URL generated by localtunnel
url = 'https://icy-numbers-refuse.loca.lt'

try:
    response = requests.get(url)
    if response.status_code == 200:
        data = response.json()
        if 'content' in data:
            print(data['content'])
        else:
            print("Content property not found in the response.")
    else:
        print("Failed to fetch data from the server. Status code:", response.status_code)
except requests.RequestException as e:
    print("Error:", e)
